name: efood_multivendor
description: A new Flutter application.
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: 4.6.6
  shared_preferences: 2.2.2
  connectivity: 3.0.6
  firebase_core: 2.24.2
  firebase_messaging: 14.7.10
  flutter_local_notifications: 16.3.0
  path_provider: 2.1.2
  url_strategy: 0.2.0
  pin_code_fields: 8.0.1
  geolocator: 10.1.0
  google_maps_flutter: 2.5.2
  google_maps_flutter_web: 0.5.4+3
  flutter_typeahead: 4.3.7
  carousel_slider: 4.2.1
  shimmer_animation: 2.1.0+1
  image_picker: 0.8.5+3
  universal_html: 2.0.8
  flutter_inappwebview: ^5.7.1+2
  url_launcher: 6.2.3
  http: 1.1.2
  chewie: 1.7.4
  pointer_interceptor: 0.9.0+1
  phone_number: 1.0.0
  country_code_picker: 3.0.0
  google_sign_in: 6.2.1
  google_sign_in_web: 0.12.3+2
  flutter_facebook_auth: 6.0.3
  photo_view: 0.14.0
  dotted_border: 2.1.0
  share_plus: 7.2.1
  custom_map_markers: 0.0.2+1
  image_compression_flutter: 1.0.3
  fwfh_text_style: 2.22.8+1
  card_swiper: 3.0.1
  expandable_bottom_sheet: 1.1.1+1
  uni_links: 0.5.1
  modal_bottom_sheet:
  sign_in_with_apple: 4.3.0
  flutter_html: 3.0.0-alpha.5
  flutter_widget_from_html: 0.14.11
  intl: any
  flutter_slidable: 3.0.1
  just_the_tooltip: 0.0.12
  animated_flip_counter: 0.2.6
  extended_image: 8.2.0


dependency_overrides:
  modal_bottom_sheet: 3.0.0-pre

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/
    - assets/language/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
    - family: Tajawal
      fonts:
        - asset: assets/font/Tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/font/Tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/font/Tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/font/Tajawal/Tajawal-Black.ttf
          weight: 900